const STATUS_CREATED = 201;
const BAD_REQUEST_ERROR = 400;
const UNAUTH_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  STATUS_CREATED,
  BAD_REQUEST_ERROR,
  UNAUTH_ERROR,
  NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
};
